### ISSUE TITLE
feat: implement CBOR + COSE (backend)

### ISSUE THREAD

**Issue by jurosens** [eu-digital-green-certificates/dgca-issuance-service#4]
## Feature description

* send data to backend as JSON
* in backend
  * create CBOR
  * calculate hash
  * sign hash
  * create QR code
* return QR code

**Comment by a-trzewik** [comment]
See example implementation in kotlin (Which can be directly reused as maven dependency)
https://github.com/ehn-digital-green-development/hcert-kotlin

The kotlin code is clean and seam to be complete. it can be compiled to jvm library and used directly in java project as maven dependency.

If the functionality should be implemented on backend side than the issue should be move to dgce-issuance-service project

**Comment by a-trzewik** [comment]
Integrated as maven dependency
https://github.com/ehn-digital-green-development/hcert-kotlin
see endpoint
POST /cert/create
available in dev mode profile
