### ISSUE TITLE
Implement HEAD /dgci/{hash} instead of /dgci/status

### ISSUE THREAD

**Issue by SchulzeStTSI** [eu-digital-green-certificates/dgca-issuance-service#42]
Please implement the /dgci/status route which should return just a 200 (OK) code, 404 (NOT FOUND) or 423 (LOCKED) to a given DGCI (given in header parameter)

The route must check the dgci status "locked" in the database, return 423 if true. 404 if not available and 200 if existing in the db and unlocked.

**Comment by a-trzewik** [comment]
Do you really mean http header parameter. This seems quite uncommon for such purposes.
Please consider that HTTPD HEADER are quite often filtered out or modified by proxies.

1) Common in REST is something like this. Path parameter
HEAD /dgc/{dgci_string}
2) Or even with query parameter
GET /dgci/status?dgci={dgci_string}

If you want a HTTP HEADER please define the name for it

**Comment by SchulzeStTSI** [comment]
According to GET /dgci/{hash} we should use a HEAD call like /dgci/{hash} to obtain the status instead of /dgci/status. (hash = SHA256(DGCI) )
