### ISSUE TITLE
Swagger API Documentation

### ISSUE THREAD

**Issue by psavva** [eu-digital-green-certificates/dgca-issuance-service#7]
Dear Team, 

Please may I request for you to supply the Swagger API documentation for the dgca-issuance-service as soon as possible?

We are in the the process of integrating our country's databases for the vaccinations, Covid tests, and recovered patients, which we need to implement the integration with the DGC Issuance Service.

Thank you and Best Regards
Panayiotis Savva
Cyprus

**Comment by a-trzewik** [comment]
The Swagger API (current state of work) can be seen in running application (see branch)
http://localhost:8090/swagger-ui/
Use spring "dev" profile

**Comment by psavva** [comment]
Dear @a-trzewik 

I have checked out the branch "setupspringboot" and am not able to compile due to the hcert-kotlin dependency.
I have found dependency here: https://github.com/ehn-digital-green-development/hcert-kotlin
however, have a conflict on the versioning.  Version 0.1.6-SNAPSHOT vs the current 0.2.0-SNAPSHOT.

The kotlin library is not tagged, and have found the specific 0.1.6 revsion as this commit: 
https://github.com/ehn-digital-green-development/hcert-kotlin/commit/f5201b2dbd436ec0ec941e3105612c731eaa691d
which again does not compile with this specific revision.

I have both Kotlin Compiler and Gradle which have issued the following to compile the library:
```
gradle task compileKotlin
gradle publishToMavenLocal
```

Any help to get this running would be greatly appreciated. 
I could submit a PR once I have the information to make it easier for the others trying to compile with documented instructions if that helps :)

Best Regards
Panayiotis Savva
Special Scientist
University of Cyprus

**Comment by a-trzewik** [comment]
The general spec for this is here
https://ec.europa.eu/health/ehealth/covid-19_en
see volume 4. There are some information's to endpoints but not very exact.

To build the application you will need to set github token von maven repositories.
see
https://docs.github.com/en/packages/guides/configuring-apache-maven-for-use-with-github-packages
Please set your tokens for following ids

     <repositories>
         <repository>
           <id>dgc-github</id>
          <url>https://maven.pkg.github.com/${github.organization}/*</url>
       </repository>
       <repository>
           <id>ehd-github</id>
          <url>https://maven.pkg.github.com/ehn-digital-green-development/*</url>
        </repository>
     </repositories>

see pom.xml
After it you will not need to compile the dependent projects by your own.
The current hcert-kotlin ist 2.0-SNAPSHOT please update your project (see)
https://github.com/ehn-digital-green-development/hcert-kotlin/blob/main/build.gradle.kts

**Comment by psavva** [comment]
Thank you very much @a-trzewik 
I have the image up and running now.

I will post a small howto compile so others can follow the same.
I'm using VSCode, and will provide the steps required from that.

**Comment by a-trzewik** [comment]
See release files (open_api.json)
