### ISSUE TITLE
adjust expiration duration

### ISSUE THREAD

**Issue by ggrund-tsi** [eu-digital-green-certificates/dgca-issuance-service#77]

**Comment by a-trzewik** [comment]
There is new field expirationDuration with duration time in seconds
for dgc init method

POST /dgci/issue

{
    "id": "1_NfdXEEmPKVC7msFAALG-lXY0jZrdJ6uNCoyKfxp4lhg",
    "dgci": "URN:UVCI:V1:DE:EE9BQBW3QVPBBAH28QBA4AKS7B",
    "kid": "jd4FUVxAJjY=",
    "algId": -7,
    "countryCode": "DE",
    "expired": 1654932585,
    "expiredDuration": 31536000
}
