### ISSUE TITLE
DgcGatewayConnectorRestClient could not be found

### ISSUE THREAD

**Issue by egobsv** [eu-digital-green-certificates/dgca-issuance-service#83]
Hello everyone,

I am trying to set up and test the Gateway and Issuance Service. I am using the official docker images, and have a running instance of the gateway at https://mytest.local
I have added an instance of ENVOY in front of the gateway and I am passing the necessary X-SSL-* headers.
I followed the instructions and I am able to  to retrieve the trust list using a registered self-signed client certificate.
 
Now I ma trying to setup Issuance Service and the Gateway Connector;  I have created the necessary certificates and have added the properties as explained in eu-digital-green-certificates/dgc-lib through the docker-compose file: 

     - DGC_GATEWAY_CONNECTOR_ENABLED=true
      - DGC_GATEWAY_CONNECTOR_ENDPOINT=https://mytest.local
      - DGC_GATEWAY_CONNECTOR_DISABLE-UPLOAD-CERTIFICATE-CHECK=false
      - DGC_GATEWAY_CONNECTOR_PROXY_ENABLED=false
      - DGC_GATEWAY_CONNECTOR_PROXY_HOST=
      - DGC_GATEWAY_CONNECTOR_PROXY_PORT=-1
      - DGC_GATEWAY_CONNECTOR_MAX-CACHE-AGE=300
      - DGC_GATEWAY_CONNECTOR_TLS-TRUST-STORE_PATH=certs/tls-trust.p12
      - DGC_GATEWAY_CONNECTOR_TLS-TRUST-STORE_PASSWORD=secret
      - DGC_GATEWAY_CONNECTOR_TLS-KEY-STORE_PATH=certs/tls-key.p12
      - DGC_GATEWAY_CONNECTOR_TLS-KEY-STORE_PASSWORD=secret
      - DGC_GATEWAY_CONNECTOR_TLS-KEY-STORE_ALIAS=tlskey1
      - DGC_GATEWAY_CONNECTOR_TRUST-ANCHOR_PATH=certs/ta.jks
      - DGC_GATEWAY_CONNECTOR_TRUST-ANCHOR_PASSWORD=secret
      - DGC_GATEWAY_CONNECTOR_TRUST-ANCHOR_ALIAS=anchor

 When starting the service I get the following error:

///-----
ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'certPublisherController' defined in URL [jar:file:/app/app.jar!/BOOT-INF/classes!/eu/europa/ec/dgc/issuance/restapi/controller/CertPublisherController.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'certKeyPublisherServiceImpl' defined in URL [jar:file:/app/app.jar!/BOOT-INF/classes!/eu/europa/ec/dgc/issuance/service/CertKeyPublisherServiceImpl.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'dgcGatewayUploadConnector' defined in URL [jar:file:/app/app.jar!/BOOT-INF/lib/dgc-lib-0.4.0.jar!/eu/europa/ec/dgc/gateway/connector/DgcGatewayUploadConnector.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'eu.europa.ec.dgc.gateway.connector.client.DgcGatewayConnectorRestClient' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}

***************************
 APPLICATION FAILED TO START
 ***************************
Description:
 Parameter 0 of constructor in eu.europa.ec.dgc.gateway.connector.DgcGatewayUploadConnector required a bean of type 'eu.europa.ec.dgc.gateway.connector.client.DgcGatewayConnectorRestClient' that could not be found.
///-----

All containers are running  inside the same Debian 10 virtual machine. 

Thank you in advance for your comments and suggestions.
Eric.

**Comment by f11h** [comment]
Can you please check if the pathes to you key- and truststores are correct?

**Comment by egobsv** [comment]
I can confirm that the keystore and truststore exist and the alias names are correct. I also went inside the container and verified  that the files are available at /app/certs.  I also tried adding the files into the Jar and used classpath, got the same error.

If it is of any help, the last part of the error message shows this line:
```
Action:
Consider defining a bean of type 'eu.europa.ec.dgc.gateway.connector.client.DgcGatewayConnectorRestClient' in your configuration.
```
BTW, this error only happens when I enable the Gateway Connector, if disabled I am able to use the service from the issuance-web container.

**Comment by egobsv** [comment]
I made some progress, it seems as though it works fine if the Gateway Connector values are set inside the application.yml file (then compile and rebuild image). Not sure why this is different from passing the environment variables from the docker-compose.yml.

**Comment by f11h** [comment]
Ah I see the problem - You've used "-" in the env var names. The "-" is not a legal character for these names. You have to just remove them and it should work.

**Comment by egobsv** [comment]
Amazing, I would have never gotten that without your help. Thank you!
